### ISSUE TITLE
Partial NULL embeddings

### ISSUE THREAD

**Issue by Nishanth-Gobi** [supabase-community/chatgpt-your-files#35]
# Bug report

## Describe the bug

On file uploads, the embedding function fails to create vectors for some of the chunks with the below message,

```
InvalidWorkerCreation: worker did not respond in time
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:155:15)
    at async Object.handler (file:///home/deno/main/index.ts:153:22)
    at async respond (ext:sb_core_main_js/js/http.js:162:14) {
  name: "InvalidWorkerCreation"
}
```

I am using the new `Supabase.ai.Session()` API and am on Edge `v1.53.3`, but it still happens sometimes at random. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run main locally
2. Upload a couple of markdown files one after the other

## Expected behavior

All chunks to have their corresponding vectors.

## Screenshots

![image](https://github.com/supabase-community/chatgpt-your-files/assets/55394089/97a97d15-bfbd-4808-b004-5d1f7dee6be1)

## System information

- OS: macOS
- Version of supabase-js: latest
- Version of Node.js: 22.1.0

## Additional context

@gregnr this seems to be different from what you mentioned could be the [reason](https://github.com/supabase-community/chatgpt-your-files/issues/30#issuecomment-2118902094) for partial NULLs in #30

**Comment by gregnr** [comment]
Very strange @Nishanth-Gobi, thanks for reporting. You're the first I've seen that has experienced this with the new `Supabase.ai` API. Would you mind submitting as issue on the [`edge-runtime`](https://github.com/supabase/edge-runtime/issues/new/choose) with this error (and link back to this issue)?

**Comment by nathanaeng** [comment]
I'm experiencing this as well.

**Comment by landmann** [comment]
I have this exact error, but I'm pretty sure it's because the local supabase_url() is wrong. I first set it as `'http://api.supabase.internal:8000'`, as stated in the docs, but that didn't resolve to anything, so then I set it as `http://127.0.0.1:44321`, which is my local db url, and got the same error.

Maybe I'm wrong though, but this seems to me like it is it.

**Comment by MeXaaR** [comment]
HI, I am having the same problem. I have some null but i have this log in the edge function logs
event loop error: Uncaught null

so it processes  all embedding but it saves to the db around 4 (on eleven) and then there is this loop error.

**Comment by gregnr** [comment]
@Nishanth-Gobi did you ever solve this?

@MeXaaR can you confirm you are also getting the `InvalidWorkerCreation: worker did not respond in time` error? If not let's open a new issue to discuss.

**Comment by Snoopie007** [comment]
i ran this with the new supabase ai and it always gives me a  @gregnr event loop error: Uncaught null. I don't understand why i tried everything but I know it issue comes from generating embedding don't know what is causing the issue. I tried using batch size of 2 and it works fine but anything beyond that it just gives me this error.

 {
  "event_message": "event loop error: Uncaught null",
  "id": "06872294-2a47-4f59-9d1e-ceb59a14a2b8",
  "metadata": [
    {
      "boot_time": null,
      "cpu_time_used": null,
      "deployment_id": "cganuxgoiziajyjkdikp_e33db286-4d78-45b9-87f1-b4c72dd40adb_7",
      "event_type": "UncaughtException",
      "execution_id": "e88d9a21-fa48-4f86-9f85-aefe6a42556a",
      "function_id": "e33db286-4d78-45b9-87f1-b4c72dd40adb",
      "level": "error",
      "memory_used": [],
      "project_ref": "cganuxgoiziajyjkdikp",
      "reason": null,
      "region": "us-east-1",
      "served_by": "supabase-edge-runtime-1.67.3 (compatible with Deno v1.45.2)",
      "timestamp": "2025-06-08T18:42:10.041Z",
      "version": "7"
    }
  ],
  "timestamp": 1749408131938013
}
